<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../bench/FilenameSearch.Core/FilenameSearch.Core.csproj" />
    <ProjectReference Include="../../bench/route_c/RouteC.csproj" />
  </ItemGroup>
</Project>
