#!/usr/bin/env python3
import unicodedata as ud
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / 'src' / 'unicode_tables.rs'
MAX = 0x110000

ccc=[]
decomp=[]
comp=[]
fold=[]
decomp_data=[]
fold_data=[]

for cp in range(MAX):
    try: ch=chr(cp)
    except ValueError: continue
    c=ud.combining(ch)
    if c:
        ccc.append((cp,c))
    d=ud.decomposition(ch)
    if d and not d.startswith('<'):
        seq=[int(x,16) for x in d.split()]
        off=len(decomp_data); decomp_data.extend(seq); decomp.append((cp,off,len(seq)))
    f=ch.casefold()
    if f != ch:
        seq=[ord(x) for x in f]
        off=len(fold_data); fold_data.extend(seq); fold.append((cp,off,len(seq)))

# Canonical composition pairs: direct canonical decompositions of length 2 that NFC recomposes.
for cp, off, ln in decomp:
    if ln != 2: continue
    a,b=decomp_data[off:off+2]
    s=chr(a)+chr(b)
    if ud.normalize('NFC', s) == chr(cp):
        comp.append((a,b,cp))
comp.sort()

with OUT.open('w', encoding='utf-8', newline='\n') as w:
    w.write('// Generated by tools/generate_unicode_tables.py; DO NOT EDIT.\n')
    w.write(f'pub const UNICODE_VERSION: &str = {ud.unidata_version!r};\n'.replace("'", '"'))
    w.write('#[rustfmt::skip]\n')
    w.write('pub static CCC: &[(u32,u8)] = &[\n')
    for cp,c in ccc: w.write(f'({cp},{c}),')
    w.write('\n];\n')
    w.write('#[rustfmt::skip]\n')
    w.write('pub static DECOMP_INDEX: &[(u32,u32,u8)] = &[\n')
    for cp,off,ln in decomp: w.write(f'({cp},{off},{ln}),')
    w.write('\n];\n')
    w.write('#[rustfmt::skip]\n')
    w.write('pub static DECOMP_DATA: &[u32] = &[\n')
    for x in decomp_data: w.write(f'{x},')
    w.write('\n];\n')
    w.write('#[rustfmt::skip]\n')
    w.write('pub static COMPOSE: &[(u32,u32,u32)] = &[\n')
    for a,b,c in comp: w.write(f'({a},{b},{c}),')
    w.write('\n];\n')
    w.write('#[rustfmt::skip]\n')
    w.write('pub static CASEFOLD_INDEX: &[(u32,u32,u8)] = &[\n')
    for cp,off,ln in fold: w.write(f'({cp},{off},{ln}),')
    w.write('\n];\n')
    w.write('#[rustfmt::skip]\n')
    w.write('pub static CASEFOLD_DATA: &[u32] = &[\n')
    for x in fold_data: w.write(f'{x},')
    w.write('\n];\n')
print('unicode', ud.unidata_version)
print('ccc', len(ccc), 'decomp', len(decomp), 'compose', len(comp), 'fold', len(fold))
